language: cpp

script:
        - mkdir ./plib-build
        - cd ./plib-build
        - cmake ..
        - make && make test

os:
        - linux
        - osx

compiler:
        - clang
        - gcc
