language: cpp

branches:
        only: master

before_install:
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-test-dev ; fi

script:
        - mkdir ./plib-build
        - cd ./plib-build
        - cmake ..
        - make && make test

os:
        - linux
        - osx

compiler:
        - clang
        - gcc

addons:
        coverity_scan:
                project:
                        name: "saprykin/plib"
                        description: "Highly portable C system library"
        notification_email: xelfium@gmail.com
        build_command_prepend: "mkdir ./plib-build; cd ./plib-build; cmake .."
        build_command: "make"
        branch_pattern: coverity_scan
