language: cpp

branches:
        only: master

before_install:
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-test-dev ; fi

script:
        - mkdir ./plib-build
        - cd ./plib-build
        - cmake ..
        - make && make test

os:
        - linux
        - osx

compiler:
        - clang
        - gcc
