language: cpp

branches:
        only:
                - master
                - coverity_scan

before_install:
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq ; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libboost-test-dev ; fi

script:
        - mkdir ./plib-build
        - cd ./plib-build
        - cmake ..
        - make
        - if [ "${COVERITY_SCAN_BRANCH}" != 1 ]; then make test ; fi

os:
        - linux
        - osx

compiler:
        - clang
        - gcc

addons:
        coverity_scan:
                project:
                        name: "saprykin/plib"
                        description: "Highly portable C system library"
                notification_email: xelfium@gmail.com
                build_command_prepend: "mkdir ./plib-build; cd ./plib-build; cmake .."
                build_command: "make"
                branch_pattern: coverity_scan
