environment:
        matrix:
                - CMAKE_GENERATOR: "MinGW Makefiles"
                  USE_MINGW:       "1"
                - CMAKE_GENERATOR: "Visual Studio 9 2008"
                  USE_OLD_MSBUILD: "1"
                - CMAKE_GENERATOR: "Visual Studio 10 2010"
                - CMAKE_GENERATOR: "Visual Studio 10 2010 Win64"
                - CMAKE_GENERATOR: "Visual Studio 11 2012"
                - CMAKE_GENERATOR: "Visual Studio 11 2012 Win64"
                - CMAKE_GENERATOR: "Visual Studio 12 2013"
                - CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
                - CMAKE_GENERATOR: "Visual Studio 14 2015"
                - CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"

os: Visual Studio 2015

configuration: Release

version: 0.0.1.{build}

branches:
        only:
                - master
                - appveyor_test

clone_folder: c:\projects\plib

before_build:
        - cd c:\projects
        - mkdir plib-build
        - cd plib-build
        - if "%APPVEYOR_REPO_BRANCH%"=="appveyor_test" set "BOOST_ARGS=-DPLIB_TESTS_STATIC=ON -DBOOST_ROOT=C:\Libraries\boost_1_59_0"
        - if "%USE_MINGW%"=="1" set "PATH=C:\MinGW\bin;C:\Program Files (x86)\CMake\bin"
        - if "%USE_MINGW%"=="1" set "BUILD_TYPE=-DCMAKE_BUILD_TYPE=%configuration%"
        - cmake -G"%CMAKE_GENERATOR%" %BOOST_ARGS% c:\projects\plib

build_script:
        - if "%USE_OLD_MSBUILD%"=="1" set "PATH=C:\Windows\Microsoft.NET\Framework\v3.5;%PATH%"
        - if "%USE_MINGW%"=="1" (mingw32-make) else (msbuild /verbosity:normal c:\projects\plib-build\PLib.sln)

test_script:
        - cd c:\projects\plib-build
        - ctest -C Release
