environment:
        matrix:
                - CMAKE_GENERATOR: "Visual Studio 9 2008"
                - CMAKE_GENERATOR: "Visual Studio 9 2008 Win64"
                - CMAKE_GENERATOR: "Visual Studio 10 2010"
                - CMAKE_GENERATOR: "Visual Studio 10 2010 Win64"
                - CMAKE_GENERATOR: "Visual Studio 11 2012"
                - CMAKE_GENERATOR: "Visual Studio 11 2012 Win64"
                - CMAKE_GENERATOR: "Visual Studio 12 2013"
                - CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
                - CMAKE_GENERATOR: "Visual Studio 14 2015"
                - CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"

os: Visual Studio 2015

configuration: Release

version: 0.0.1.{build}

branches:
        only:
                - master

clone_folder: c:\projects\plib

platform:
        - x64

before_build:
        - cd c:\projects
        - mkdir plib-build
        - cd plib-build
        - cmake -DCMAKE_BUILD_TYPE=Release -G"%CMAKE_GENERATOR%" c:\projects\plib

build_script:
        - cd c:\projects\plib-build
        - nmake

test_script:
        - ctest
