environment:
        matrix:
                - CMAKE_GENERATOR: "MinGW Makefiles"
                  USE_MINGW:       "1"
                - CMAKE_GENERATOR: "MSYS Makefiles"
                  USE_MSYS:        "1"
                - CMAKE_GENERATOR: "Visual Studio 9 2008"
                  USE_OLD_MSBUILD: "1"
                - CMAKE_GENERATOR: "Visual Studio 10 2010"
                - CMAKE_GENERATOR: "Visual Studio 10 2010 Win64"
                - CMAKE_GENERATOR: "Visual Studio 11 2012"
                - CMAKE_GENERATOR: "Visual Studio 11 2012 Win64"
                - CMAKE_GENERATOR: "Visual Studio 12 2013"
                - CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
                - CMAKE_GENERATOR: "Visual Studio 14 2015"
                - CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"

os: Visual Studio 2015

configuration: Release

version: 0.0.1.{build}

branches:
        only:
                - master
                - appveyor_test

clone_folder: c:\projects\plib

before_build:
        - cd c:\projects
        - mkdir plib-build
        - cd plib-build
        - ps: >-
                if ($env:APPVEYOR_REPO_BRANCH -eq "appveyor_test") {
                        $env:BOOST_ARGS = "-DPLIB_TESTS_STATIC=ON -DBOOST_ROOT=C:\Libraries\boost_1_59_0"
                }
        - ps: >-
                if ($env:USE_MINGW -eq "1") {
                        $env:PATH = "PATH=C:\MinGW\bin;C:\Program Files (x86)\CMake\bin"
                        $env:BUILD_TYPE = "-DCMAKE_BUILD_TYPE=" + $env:CONFIGURATION
                } elseif ($env:USE_MSYS -eq "1") {
                        $env:BUILD_TYPE = "-DCMAKE_BUILD_TYPE=" + $env:CONFIGURATION
                        c:\msys64\msys2_shell.bat
                } elseif ($env:USE_OLD_MSBUILD -eq "1") {
                        $env:PATH = "C:\Windows\Microsoft.NET\Framework\v3.5;" + $env:PATH
                }
        - cmake %BUILD_TYPE% -G"%CMAKE_GENERATOR%" %BOOST_ARGS% c:\projects\plib

build_script:
        - ps: >-
                if ($env:USE_MINGW -eq "1") {
                        mingw32-make
                } elseif ($env:USE_MSYS -eq "1") {                        
                        make
                } else {
                        msbuild /verbosity:normal c:\projects\plib-build\PLib.sln
                }

test_script:
        - cd c:\projects\plib-build
        - ctest -C Release
