environment:
        matrix:
                - CMAKE_GENERATOR: "Visual Studio 9 2008"
                  USE_OLD_MSBUILD: "1"
                - CMAKE_GENERATOR: "Visual Studio 9 2008 Win64"
                  USE_OLD_MSBUILD: "1"
                - CMAKE_GENERATOR: "Visual Studio 10 2010"
                - CMAKE_GENERATOR: "Visual Studio 10 2010 Win64"
                - CMAKE_GENERATOR: "Visual Studio 11 2012"
                - CMAKE_GENERATOR: "Visual Studio 11 2012 Win64"
                - CMAKE_GENERATOR: "Visual Studio 12 2013"
                - CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
                - CMAKE_GENERATOR: "Visual Studio 14 2015"
                - CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"

os: Visual Studio 2015

configuration: Release

version: 0.0.1.{build}

branches:
        only:
                - master

clone_folder: c:\projects\plib

before_build:
        - cd c:\projects
        - mkdir plib-build
        - cd plib-build
        - cmake -G"%CMAKE_GENERATOR%" -DPLIB_TESTS_STATIC=ON -DBOOST_ROOT=C:\Libraries\boost_1_59_0 c:\projects\plib

build_script:
        - if "%USE_OLD_MSBUILD%"=="1" set PATH=C:\Windows\Microsoft.NET\Framework\v3.5;%PATH%
        - msbuild /verbosity:quiet c:\projects\plib-build\PLib.sln

test_script:
        - ctest
