environment:
        matrix:
                - CMAKE_GENERATOR: "MinGW Makefiles"
                  USE_MINGW:       "1"
                - CMAKE_GENERATOR: "MSYS Makefiles"
                  USE_MSYS:        "1"
                - CMAKE_GENERATOR: "Visual Studio 9 2008"
                  USE_OLD_MSBUILD: "1"
                - CMAKE_GENERATOR: "Visual Studio 10 2010"
                - CMAKE_GENERATOR: "Visual Studio 10 2010 Win64"
                - CMAKE_GENERATOR: "Visual Studio 11 2012"
                - CMAKE_GENERATOR: "Visual Studio 11 2012 Win64"
                - CMAKE_GENERATOR: "Visual Studio 12 2013"
                - CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
                - CMAKE_GENERATOR: "Visual Studio 14 2015"
                - CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"

os: Visual Studio 2015

configuration: Release

version: 0.0.1.{build}

branches:
        only:
                - master
                - appveyor_test

clone_folder: c:\projects\plib

build_script:
        - cmd: c:\projects\plib\contrib\appveyor\build_main.bat
